### PR TITLE
Clean up Makefile and document tests

### PR DESCRIPTION
**Pull request by SchmErik**
This pull request contains updates to documentation and a new target for the Makefile that runs conformance tests.

### CODE REVIEW

**Comment by SchmErik** [comment]
Note: this pull request compares all existing test output against output generated by uplc. The uplc programs are evaluated by passing the --results-only tag. This is done because the UPLC files are evaluated by the semantics and we need to test the output with the output from uplc (aka the reference implementation).

**Comment by ChristianoBraga** [comment]
Sometimes we want to check the output of other cells apart from the k cell. Or not just the top of the stack on the k cell. Conformance does not allow that.

**Comment by SchmErik** [comment]
> Sometimes we want to check the output of other cells apart from the k cell. Or not just the top of the stack on the k cell. Conformance does not allow that.

I agree. We could write tests that specifically compare the output in other cells. However, even in this case I think we should still compare that program evaluation's K cell output against the output that we get from running uplc. Here's how I'm thinking about it: any test that gets run by the command `kplc run` should at least have the k cell output compared to uplc's output. We could check other cells in a separate test pass (or maybe the same one) but at the minimum, I think all tests should be run like this. When we get into proofs, I don't know if we need to regress to a reference implementation so I don't think we have any upstream tools that we're doing this with... Now that I think about it, should we be comparing kplc's output with both uplc and kplc output? @ChristianoBraga and @ehildenb what do you think??

**Comment by ChristianoBraga** [comment]
I agree that we should always compare the top of the stack on the k cell
with uplc’s output.

Em seg., 17 de jan. de 2022 às 22:59, Erik Kaneda ***@***.***>
escreveu:

**Review by ChristianoBraga — APPROVED** [review]

**Pull request merged**
